name: Run Weather Agent

on:
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip              
          pip install google-generativeai --upgrade              
          pip install google-adk litellm --upgrade


          pip install -r requirements.txt

      - name: Run agent script
        run: python agents/weather/main.py
