name: Run Weather Agent

on:
  workflow_dispatch:

jobs:
  run-weather-agent:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pip and dependencies
      run: |
        python -m ensurepip --upgrade       # Ensures pip is installed
        python -m pip install --upgrade pip # Upgrades pip
        pip install -r requirements.txt     # Installs your dependencies

    - name: Run weather agent
      run: python agents/weather/main.py
